// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOXJPjyyVGdn8R1OpnRXn0KGZowLZNNA',
    appId: '1:248771283120:web:853f31bf7194dc22809375',
    messagingSenderId: '248771283120',
    projectId: 'chat-app-799c0',
    authDomain: 'chat-app-799c0.firebaseapp.com',
    storageBucket: 'chat-app-799c0.firebasestorage.app',
    measurementId: 'G-V2KE5JJET5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhPLvvx9SK4OgerU9-DdI2M3L1j3TnKcs',
    appId: '1:248771283120:android:19366c297df6b15b809375',
    messagingSenderId: '248771283120',
    projectId: 'chat-app-799c0',
    storageBucket: 'chat-app-799c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXQzrz_9Z2-em-nfXhFYi3eetBPe38_o',
    appId: '1:248771283120:ios:d2ae40cecc8c4062809375',
    messagingSenderId: '248771283120',
    projectId: 'chat-app-799c0',
    storageBucket: 'chat-app-799c0.firebasestorage.app',
    iosBundleId: 'com.example.scholarChat',
  );

}